name: Codespell

on:
  push:
    braches : ["main", "new-feature-github-actions"]
  pull_request:
  
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        path: ./src/
        skip: "*.lua,*.ui"
        ignore_words_list: "doubleclick,msdos"
      